SubChunk {
    registry: {
        blocks: [Object],
            blocksByName: [Object],
                blocksArray: [Array],
                    blocksByStateId: [Object],
                        blockMappings: undefined,
                            blockStates: [Array],
                                blockCollisionShapes: [Object],
                                    biomes: [Object],
                                        biomesByName: [Object],
                                            biomesArray: [Array],
                                                items: [Object],
                                                    itemsByName: [Object],
                                                        itemsArray: [Array],
                                                            foods: undefined,
                                                                foodsByName: undefined,
                                                                    foodsArray: undefined,
                                                                        recipes: [Object],
                                                                            instruments: [Object],
                                                                                instrumentsArray: [Array],
                                                                                    materials: [Object],
                                                                                        enchantments: [Object],
                                                                                            enchantmentsByName: [Object],
                                                                                                enchantmentsArray: [Array],
                                                                                                    mobs: { },
        objects: { },
        entities: [Object],
            entitiesByName: [Object],
                entitiesArray: [Array],
                    windows: [Object],
                        windowsByName: [Object],
                            windowsArray: [Array],
                                protocol: [Object],
                                    protocolComments: undefined,
                                        protocolYaml: [Array],
                                            defaultSkin: [Object],
                                                version: [Version],
                                                    effects: [Object],
                                                        effectsByName: [Object],
                                                            effectsArray: [Array],
                                                                attributes: undefined,
                                                                    attributesByName: undefined,
                                                                        attributesArray: undefined,
                                                                            particles: undefined,
                                                                                particlesByName: undefined,
                                                                                    particlesArray: undefined,
                                                                                        language: undefined,
                                                                                            blockLoot: undefined,
                                                                                                blockLootArray: undefined,
                                                                                                    entityLoot: undefined,
                                                                                                        entityLootArray: undefined,
                                                                                                            commands: undefined,
                                                                                                                loginPacket: undefined,
                                                                                                                    mapIcons: undefined,
                                                                                                                        mapIconsByName: undefined,
                                                                                                                            mapIconsArray: undefined,
                                                                                                                                tints: undefined,
                                                                                                                                    type: 'bedrock',
                                                                                                                                        isNewerOrEqualTo: [Function(anonymous)],
                                                                                                                                            isOlderThan: [Function(anonymous)],
                                                                                                                                                supportFeature: [Function(anonymous)]
    },
    Block: [class Block],
        y: 5,
            palette: [[Array]],
                blocks: [[PalettedStorage]],
                    subChunkVersion: 8,
                        hash: null,
                            updated: true,
                                blockLight: PalettedStorage {
        bitsPerBlock: 4,
            blocksPerWord: 8,
                wordsCount: 512,
                    mask: 15,
                        array: [Uint32Array of 512 items { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ... }]
    },
    skyLight: PalettedStorage {
        bitsPerBlock: 4,
            blocksPerWord: 8,
                wordsCount: 512,
                    mask: 15,
                        array: [Uint32Array of 512 items { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 , ... }]
    }
}